### ISSUE TITLE
Vertus query

### ISSUE THREAD

**Issue by xndjzx** [NotMRGH/VertusClaimer#1]
Sir. How to run it with query not API?? Please help. I run it in termux

**Comment by NotMRGH** [comment]
Hello,

I do not have any information regarding Termius. If you are referring to the query ID that Telegram provides, and you're trying to inspect it, you can retrieve the query ID through Telegram Web. As for my bot, it does not work with this system, and you will need to manually log in the your account in bot. Additionally, you will need both the API key and API hash in order to proceed with this task.

**Comment by xndjzx** [comment]
Thanks. Yes I know how to get query. I thought your script work with add query in it. Thanks for the info bro.
